### ISSUE TITLE
hardcoded paths

### ISSUE THREAD

**Issue by alvaralmstedt** [parvanehnikpour2024/Parvaneh_course_Project#2]
There are hardcoded paths in the script that point to excel files with a static names. It would be better to give the inputs as arguments.

**Comment by parvanehnikpour2024** [comment]
Update: Instead of using hardcoded paths, I have added command-line arguments (using argparse) to the script. Now, you can pass the file paths as inputs when running the script. In terminal just write:

**python RNA_seq_analysis_final.py --file1 path/to/run1.xlsx --file2 path/to/run2.xlsx --metadata path/to/Samples_metadata.xlsx**

Note: Replace path/to/... with the actual file paths

**Comment by alvaralmstedt** [comment]
Hi you're on the right track but you still have it hardcoded on line 56 and 57. Please fix! :)


```
(parvaneh) alvaralmstedt@MacBook-Pro-4 Parvaneh_course_Project % python RNA_seq_analysis_final.py --file1 test_data/run1.xlsx --file2 test_data/run2.xlsx --metadata test_data/Samples_metadata.xlsx
Traceback (most recent call last):
  File "/Users/alvaralmstedt/repos/course_students_HT2024/parvaneh/Parvaneh_course_Project/RNA_seq_analysis_final.py", line 56, in <module>
    file1 = pd.read_excel("run1.xlsx")  # Make sure the file is in the same directory
  File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
  File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
  File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
  File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'run1.xlsx'
```

**Comment by parvanehnikpour2024** [comment]
> Hi you're on the right track but you still have it hardcoded on line 56 and 57. Please fix! :)
> 
> ```
> (parvaneh) alvaralmstedt@MacBook-Pro-4 Parvaneh_course_Project % python RNA_seq_analysis_final.py --file1 test_data/run1.xlsx --file2 test_data/run2.xlsx --metadata test_data/Samples_metadata.xlsx
> Traceback (most recent call last):
>   File "/Users/alvaralmstedt/repos/course_students_HT2024/parvaneh/Parvaneh_course_Project/RNA_seq_analysis_final.py", line 56, in <module>
>     file1 = pd.read_excel("run1.xlsx")  # Make sure the file is in the same directory
>   File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
>     io = ExcelFile(
>   File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
>     ext = inspect_excel_format(
>   File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
>     with get_handle(
>   File "/Users/alvaralmstedt/miniconda3/envs/parvaneh/lib/python3.9/site-packages/pandas/io/common.py", line 882, in get_handle
>     handle = open(handle, ioargs.mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'run1.xlsx'
> ```

Hi and thanks for your comment. Now I fixed them. Hope it works with no error.

**Comment by alvaralmstedt** [comment]
Great it works!
